# Single Node Training

In [1]:
import sys
sys.path.append('..')

import tensorflow as tf
from narla.node import Node

tf.random.set_seed(123)

In [2]:
node = Node()

In [3]:
# Training data
X = tf.random.uniform((100, 3))
Y = tf.random.uniform((100, 1))

### Storing seperate tapes

In [4]:
for i in range(10):
    tapes = []
    outputs = []

    for x in X:
        _x = tf.reshape(x, (1, 3))
        with tf.GradientTape(persistent=True) as tape:
            outputs.append(node(_x)[0])
            tapes.append(tape)

    opt = tf.keras.optimizers.SGD(learning_rate=0.01)
    losses = 0

    for tape, output, y in zip(tapes, outputs, Y):
        tape.__enter__()
        loss = (output - y)**2
        tape.__exit__(None, None, None)
        
        losses += loss
        
    grads = tape.gradient(loss, node.trainable_variables)
    opt.apply_gradients(
        zip(grads, node.variables)
    )

    print(
        losses
    )

tf.Tensor([40.26368], shape=(1,), dtype=float32)
tf.Tensor([36.33821], shape=(1,), dtype=float32)
tf.Tensor([33.724358], shape=(1,), dtype=float32)
tf.Tensor([39.702484], shape=(1,), dtype=float32)
tf.Tensor([36.986988], shape=(1,), dtype=float32)
tf.Tensor([36.317238], shape=(1,), dtype=float32)
tf.Tensor([34.84026], shape=(1,), dtype=float32)
tf.Tensor([34.626686], shape=(1,), dtype=float32)
tf.Tensor([37.487305], shape=(1,), dtype=float32)
tf.Tensor([39.679535], shape=(1,), dtype=float32)


### One Tape : Calculate loss immediately

In [4]:
opt = tf.keras.optimizers.SGD(learning_rate=0.01)
for i in range(10):
    losses = 0
    for x, y in zip(X, Y):
        _x = tf.reshape(x, (1, 3))
        with tf.GradientTape(persistent=True) as tape:
            output = node(_x)[0]        
            loss = (output - y)**2

        losses += loss
        
    grads = tape.gradient(loss, node.trainable_variables)
    opt.apply_gradients(
        zip(grads, node.variables)
    )

    print(
        losses
    )

tf.Tensor([40.26368], shape=(1,), dtype=float32)
tf.Tensor([36.33821], shape=(1,), dtype=float32)
tf.Tensor([33.724358], shape=(1,), dtype=float32)
tf.Tensor([39.702484], shape=(1,), dtype=float32)
tf.Tensor([36.986988], shape=(1,), dtype=float32)
tf.Tensor([36.317238], shape=(1,), dtype=float32)
tf.Tensor([34.84026], shape=(1,), dtype=float32)
tf.Tensor([34.626686], shape=(1,), dtype=float32)
tf.Tensor([37.487305], shape=(1,), dtype=float32)
tf.Tensor([39.679535], shape=(1,), dtype=float32)
